export const tvshows = [
  {
    id: 1418,
    name: 'The Big Bang Theory',
    countries: [
      'US',
    ],
    firstAired: '2007-09-24',
    poster: 'http://image.tmdb.org/t/p/w342/wQoosZYg9FqPrmI4zeCLRdEbqAB.jpg',
    episodes: {},
    followed: false,
  },
  {
    id: 41727,
    name: 'Banshee',
    countries: [
      'US',
    ],
    firstAired: '2013-01-11',
    poster: 'http://image.tmdb.org/t/p/w342/fvocBFChMERoxWb7MMuTsUqWEis.jpg',
    episodes: {},
    followed: true,
  },
  {
    id: 40675,
    name: 'DCI Banks',
    countries: [
      'GB',
    ],
    firstAired: '2010-09-27',
    poster: 'http://image.tmdb.org/t/p/w342/77pq0pNxN3voonu0dfYy5EJnMfx.jpg',
    episodes: {},
    followed: false,
  },
  {
    id: 62130,
    name: 'Banished',
    countries: [
      'GB',
    ],
    firstAired: '2015-03-05',
    poster: 'http://image.tmdb.org/t/p/w342/kFTY0Rl10TPT0qNTgPjV8bORJ1m.jpg',
    episodes: {},
    followed: false,
  },
  {
    id: 61931,
    name: 'Banana',
    countries: [
      'GB',
    ],
    firstAired: '2015-01-22',
    poster: 'http://image.tmdb.org/t/p/w342/nf9qyCIS3VkvJoXT1a9IdkbtDrx.jpg',
    episodes: {},
    followed: false,
  },
  {
    id: 12342,
    name: 'Banzai',
    countries: [
      'GB',
    ],
    firstAired: '2001-01-18',
    poster: 'http://image.tmdb.org/t/p/w342/1rq5VwXNDoyaoZwelnwql5H9tLK.jpg',
    episodes: {},
    followed: false,
  },
  {
    id: 1340,
    name: 'Banacek',
    countries: [
      'US',
    ],
    firstAired: '1972-09-13',
    poster: 'http://image.tmdb.org/t/p/w342/nFBIneZOuWNw7tOEKBQfEboRsQV.jpg',
    episodes: {},
    followed: false,
  },
  {
    id: 11479,
    name: 'Banyon',
    countries: [
      'US',
    ],
    firstAired: '1972-09-15',
    episodes: {},
    followed: false,
  },
  {
    id: 50550,
    name: 'Ban Lang Mek',
    countries: [],
    episodes: {},
    followed: false,
  },
  {
    id: 24298,
    name: 'Bananasplit',
    countries: [
      'NL',
    ],
    firstAired: '2009-02-08',
    episodes: {},
    followed: false,
  },
  {
    id: 59986,
    name: 'Glub Ban Rao Na...Ruk Ror Yoo',
    countries: [
      'TH',
    ],
    episodes: {},
    followed: false,
  },
  {
    id: 46226,
    name: 'Evangelion Shin Gekijo-ban',
    countries: [],
    episodes: {},
    followed: false,
  },
  {
    id: 43780,
    name: 'Elf-ban Kakyūsei',
    countries: [],
    episodes: {},
    followed: false,
  },
  {
    id: 56271,
    name: 'Krabeu Ban',
    countries: [],
    episodes: {},
    followed: false,
  },
  {
    id: 57902,
    name: 'Meuh Dok Rak Ban',
    countries: [
      'TH',
    ],
    episodes: {},
    followed: false,
  },
  {
    id: 9127,
    name: 'Ban This Filth',
    countries: [
      'GB',
    ],
    poster: 'http://image.tmdb.org/t/p/w342/yaRkADW8K0Y8tJvhft78KW9vZfc.jpg',
    episodes: {},
    followed: false,
  },
  {
    id: 57354,
    name: 'Ban Di Chuc Bi An',
    countries: [],
    episodes: {},
    followed: false,
  },
  {
    id: 16691,
    name: 'X-Rated: The Pop Videos They Tried to Ban',
    countries: [],
    episodes: {},
    followed: false,
  },
  {
    id: 19224,
    name: 'X-Rated: The TV They Tried to Ban',
    countries: [],
    episodes: {},
    followed: false,
  },
  {
    id: 53849,
    name: 'Imra ah fi Shaqil Tiban',
    countries: [],
    episodes: {},
    followed: false,
  },
]
